### ISSUE TITLE
Control by midi out a hardware such drum machine with Processing

### ISSUE THREAD

**Issue by chanof** [atsushieno/managed-midi#13]
Hi there, i search from long time if there is a way to control by Processing patch an hardware linked by MIDI/USB OUT of the android device?
Basically i search something like a lib for Processing or i'm able to convert my sketch into android studio and i need the android API linked to.
Thanks a lot
Gian

**Comment by atsushieno** [comment]
managed-midi is a library for .NET and MIDI, and therefore nothing is related to processing and Android per se. Therefore I'm going to close this issue regardless of whether my additional comment works for you or not.

I don't know much about recent processing capabilities, but it is more about on which platform you run your processing app. Basically Processing is Java, and all the underlying Java libraries are available.

If it is desktop, then whatever JRE provides, including javax.sound.midi, should be accessible. If I understand correctly, javax.sound.midi is based on the MIDI device management from the underlying OS (i.e. WinMM on Windows, CoreMIDI on Mac, ALSA on Linux). So you have to get your Android device connected to the desktop and make sure that it is connected as a MIDI device (either via USB or BLE). Then the device will be listed as a valid MIDI device.
