### ISSUE TITLE
dotnetcore: Doesn't seem to work at all?

### ISSUE THREAD

**Issue by mat1jaczyyy** [atsushieno/managed-midi#15]
This library doesn't seem to work at all for me.

The only MIDI output device in `MidiAccessManager.Default.Outputs` appears to be `"dummy_out"`, even though I'm sure I have multiple MIDI devices connected to my machine. This doesn't allow me to send any kind of MIDI data. MIDI input devices behave similarly, with a `"dummy_in"`.

This happens on both macOS (Sierra) and Windows (10). I'm using .NET Core 2.1 on both.

```
using System;
using System.Linq;
using Commons.Music.Midi;

namespace TestApp {
    class Program {
        static void Main(string[] args) {
            var access = MidiAccessManager.Default;
            var output = access.OpenOutputAsync(access.Outputs.Last().Id).Result;
            Console.WriteLine(access.Outputs.Last().Id);
            output.Send(new byte [] {MidiEvent.NoteOn, 0x24, 0x64}, 0, 3, 0);
        }
    }
}
```

With this example code, the console outputs `dummy_out` and the note doesn't get sent to my MIDI device. The same occurs if I replace `Last()` with `First()`, because the `Count()` of `access.Outputs` is `1`.

Is there something I'm doing wrong?

**Comment by atsushieno** [comment]
You app based on .NET Core means you are supposed to implement your platform-specific MIDI implementation by yourself. The netsdandard2.0 library is really platform neutral.

If you are using net461 desktop you will be seeing WinMM implementation on Windows. For Mac you will have to build Commons.Music.Midi.XamMacFull.csproj and use the resulting dll for the reason explained at the last section at https://dev.to/atsushieno/managed-midi-the-truly-cross-platform-net-midi-api-56hk .

**Comment by atsushieno** [comment]
Check out the latest managed-midi 1.3.1 or master. There is a new netcoreapp2.1 library that is based on Desktop version of the assembly. The limitation on Mac still applies though (there is no Xamarin.Mac for .NET Core).

**Comment by mat1jaczyyy** [comment]
Your commits got it working on Windows. I thank you for that.

About the Mac limitation, I've built Commons.Music.Midi.XamMacFull.csproj to Commons.Music.Midi.dll and I've referenced it in my C# project as well as Xamarin.Mac.dll:

```
<Reference Include="managed-midi">
  <HintPath>Commons.Music.Midi.dll</HintPath>
</Reference>
<Reference Include="xamarin-mac">
  <HintPath>Xamarin.Mac.dll</HintPath>
</Reference>
```

The code compiles, however attempting to access any method of `MidiAccessManager.Default.Inputs` or `.Outputs` causes a `System.TypeInitializationException`:

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Foundation.NSString' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at ObjCRuntime.Class.Register(Type type)
   at Foundation.NSObject.AllocIfNeeded()
   at Foundation.NSObject..ctor()
   at Foundation.NSString..ctor(String str)
   at Foundation.NSString..cctor()
   --- End of inner exception stack trace ---
   at Foundation.NSString.FromHandle(IntPtr usrhandle)
   at CoreMidi.MidiObject.GetString(IntPtr property)
   at CoreMidi.MidiEndpoint.get_Name()
   at Commons.Music.Midi.CoreMidiApi.CoreMidiPortDetails..ctor(MidiEndpoint src)
   at Commons.Music.Midi.CoreMidiApi.CoreMidiAccess.get_Outputs()+MoveNext()
   at System.Linq.Enumerable.TryGetLast[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at TestApp.Program.Main(String[] args) in /Users/mat1jaczyyy/Code/TestApp/Program.cs:line 34
```

where line 34 in my code is `Console.WriteLine(MidiAccessManager.Default.Outputs.Last().Id);`.

Is this problem what you meant when you wrote "there is no Xamarin.Mac for .NET Core" or is this a separate issue?

**Comment by atsushieno** [comment]
Did you call `NSApplication.Init()` before using any managed-midi / Xamarin.Mac bits ?

**Comment by mat1jaczyyy** [comment]
If I do attempt to call it, `The name 'NSApplication' does not exist in the current context.`. I believe I also need to write `using Xamarin.Mac` at the start, however this yields `The type or namespace name 'Xamarin' could not be found`. I believe I've referenced Xamarin.Mac.dll correctly, but I might have done a stupid mistake which I'm not seeing. Here's the code:

TestApp.csproj
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <RuntimeIdentifiers>win10-x64;osx.10.11-x64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <!--<PackageReference Include="managed-midi" Version="1.3.1" />-->
    <Reference Include="managed-midi">
      <HintPath>Commons.Music.Midi.dll</HintPath>
    </Reference>

    <!-- I'm not sure what the correct name is in the Include? -->
    <Reference Include="xamarin-mac">
      <HintPath>Xamarin.Mac.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
```

Program.cs:
```
using System;
using System.Linq;
using Commons.Music.Midi;
using Xamarin.Mac;

namespace TestApp {
    class Program {
        // MIDI Access
        static IMidiAccess access;
        static IMidiInput input;
        static IMidiOutput output;
        
        // Initialize Program
        static void Main(string[] args) {
            NSApplication.Init();
            access = MidiAccessManager.Default; 

            Console.WriteLine(access.Inputs.Last().Id);
            Console.WriteLine(access.Outputs.Last().Id);

            input = access.OpenInputAsync(access.Inputs.Last().Id).Result;
            output = access.OpenOutputAsync(access.Outputs.Last().Id).Result;

            output.Send(new byte[] {0xB0, 0x68, 0x05}, 0, 3, 0);
        }

        static void MIDIIn(object sender, MidiReceivedEventArgs e) {
            for (int i = 0; i < e.Length; i++) {
                Console.WriteLine(e.Data[i].ToString());
            }
        }
    }
}
```

**Comment by atsushieno** [comment]
Xamarin.Mac profile is either for its own or for .NET Framework (net4xx). You are targeting .NET Core. As I explained earlier, Xamarin.Mac does not support .NET Core. So you have to switch to either of those Xamarin.Mac supported frameworks.
