### ISSUE TITLE
Missing DLL - alsa-sharp.dll from repository

### ISSUE THREAD

**Issue by gitizenme** [atsushieno/managed-midi#28]
Looks like this is a build dependency that is not linked in correctly. 
`/Users/joe/Projects/Music/euclid/ext/managed-midi/Commons.Music.Midi.Desktop/CSC: Error CS0006: Metadata file '/Users/joe/Projects/Music/euclid/ext/managed-midi/external/alsa-sharp/alsa-sharp/bin/Debug/alsa-sharp.dll' could not be found (CS0006) (Commons.Music.Midi.Desktop)`

**Comment by atsushieno** [comment]
it is git submodule.
