### ISSUE TITLE
MidiPlayer doesn't provide a way to check if actual playback has stopped.

### ISSUE THREAD

**Issue by jeroenwalter** [atsushieno/managed-midi#29]
Thanks for this wonderful API! 
I'm using it to create a barrel organ emulator on the Raspberry Pi, but I'm first prototyping it on Windows.

I've come across a problem in the API though.
I need to know when the MidiPlayer is done playing, i.e. when the MidiSyncPlayer.sync_player_task is finished. Because only then can I close the MidiOutput instance.
When the MidiOutput is closed before playing is stopped, I get a Win32 exception because it tries to send a midi message to a closed, and hence, invalid handle.

MidiPlayer now only has a PauseAsync method. I propose an awaitable Stop method or something similar. 
I've forked the project, so I may end up changing the code myself, although I have a workaround for my problem right now.
I also see enough room for some small refactoring and clean up the code (move classes to their own files, etc). 
I also have a small WPF application, demonstrating how the API can be used in Windows, so maybe I will upload that too.

**Comment by atsushieno** [comment]
Thanks for the kind words!
Did you try `MidiPlayer.Finished` event? It might not have worked for you but in case you just missed it...

There would be handful (or lots) of rooms for improvements that I missed out. I definitely appreciate your feedbacks/PRs.

On `Stop` feature, you are likely right. I implement "stop" feature in my visual player in complicated way https://github.com/atsushieno/xmdsp/blob/master/Xmdsp.Models/Model.cs#L257 and that likely had better implemented (partly) in `MidiPlayer` itself.

**Comment by jeroenwalter** [comment]
The Finished event is only called when all message are played, not when you stop in the middle of a song.

**Comment by atsushieno** [comment]
Ahh, right. In that sense, having `Stop` makes more sense.

**Comment by atsushieno** [comment]
The PR is merged. This will be closed once I add the missing tests.
