### ISSUE TITLE
Sending Midi beat clock through IMidiOutput.Send

### ISSUE THREAD

**Issue by eidetic-av** [atsushieno/managed-midi#36]
I'm trying to forward incoming messages using WinMM from an IMidiInput to an IMidiOutput in the following way:

```csharp
IMidiInputInstance.MessageReceived += (object sender, MidiReceivedEventArgs e) => IMidiOutputInstance.Send(e.Data, e.Start, e.Length, e.Timestamp);
```

But whenever I attempt to forward a Beat Clock message (status 0xF8), I get thrown a NullReferenceException.

I can see the error is coming from SMF.MidiEvent.Convert, I'm just not quite understanding what is happening in there.

If I replace it with:
```csharp
public static IEnumerable<MidiEvent> Convert (byte[] bytes, int index, int size)
{
	int i = index;
	int end = index + size;
	while (i < end)
	{
		if (bytes[i] == 0xF0)
		{
			var tmp = new byte [size];
			Array.Copy (bytes, i, tmp, 0, tmp.Length);
			yield return new MidiEvent (0xF0, 0, 0, tmp);
			i += size;
		}
		else if (bytes[i] == 0xF8)
		{
			yield return new MidiEvent(0xF8, 0, 0, bytes);
			i++;
                }
		else
		{
			if (end < i + MidiEvent.FixedDataSize (bytes [i]))
				throw new Exception (string.Format ("Received data was incomplete to build MIDI status message for '{0:X}' status.", bytes[i]));
			var z = MidiEvent.FixedDataSize (bytes[i]);
			yield return new MidiEvent (bytes [i], bytes [i + 1], (byte) (z > 1 ? bytes [i + 2] : 0), null);
			i += z + 1;
		}
	}
}
```

I am then able to forward the Midi clock successfully to another device, but then any other messages (for example a NoteOn) cause the NullReference to come back.

I just do not know how to complete the IEnumerable for it to work.

According this [this page](http://midi.teragonaudio.com/tech/midispec/clock.htm), there is no data transmitted other than the status byte. But no matter how much I increment 'i' here (0, 1, 2 ,3 times) it still crashes out.

Would you be able to point me in the right direction?

**Comment by atsushieno** [comment]
Apparently managed-midi lacks support for those messages between 0xF1-0xFE...! (or 0xFF on that website, it is META event in SMF). Seriously I never had input devices that do send those messages in my life (not many though).

Instead of adding another `if` statement ther, adding other conditions in `MidiEvent.FixedDataSize()` for those F[x] messages would be better.

When I got time for this I will try to fix it with some imaginary repro data including other F[x] messages. Thanks for the report.

**Comment by atsushieno** [comment]
I added some quick code for above. If you're building from master it would be nice if you can try it.

**Comment by eidetic-av** [comment]
Thanks for acting so quick on this!

I just gave it a try, and I am still receiving a null pointer, though.

I think it comes down to the fact that Midi Clock messages contain no data.

In WinmmMidiAccess.cs at line 357:
```csharp
header.Data = Marshal.AllocHGlobal(evt.Data.Length);
````

`evt.Data` is equal to null. It seems to be set to null on line 317 of SMF.cs in the Convert IEnumerable.

**Comment by atsushieno** [comment]
Thanks for the update. I just committed a fix in master. Please reopen the issue if there's still the same issue.

**Comment by eidetic-av** [comment]
I'm getting this Exception now:

![Annotation 2019-04-23 153315](https://user-images.githubusercontent.com/13776134/56584964-2a197500-65dd-11e9-970b-a890551e7273.png)

I think the issue could stem from the WinmmMidiAccess.WinMMMidiInput.HandleData method.
The data byte[] size is being set to either 2 or 3, but I think the message is only a single byte long?

I'm not sure.

**Comment by atsushieno** [comment]
Ah, exactly. There could be code like that where I expect only 2 or 3 bytes of "short" messages elsewhere... Adding condition for 1 byte would get that code path working.

**Comment by eidetic-av** [comment]
That's what I thought initially but it is resulting in more errors for me later on. I will keep trying to debug and track these down.

**Comment by eidetic-av** [comment]
Is there a reason why the length parameter is passed around at all? Could it not be inferred by the size of the data array?

**Comment by atsushieno** [comment]
For new offset/length arguments, they are all for possible optimization. It is typical "array, offset, length" set of arguments. Whenever arrays are involved, assuming zero-starting array means extra array allocations. And whenever the size matters (which is almost always true), there should be length.

There will be default values for those index and length once I remove those [Obsolete]d methods. Until that happens they have no default parameters to avoid ambiguity with the old method.

**Comment by atsushieno** [comment]
I just made two more relevant fixes at https://github.com/atsushieno/managed-midi/commit/4d9b713.

I will be adding some conversion tests once I come up with some MIDI data that contains those Fn bytes (for now there are some new  tests wrt it).

**Comment by atsushieno** [comment]
Now that I have added some tests for MidiEvent.Convert(), I'm going to close this issue. (Tests for platform-specific backends are not going to run, in practice...) If you still have problems please reopen it or create another issue. Thanks!
