### ISSUE TITLE
Don't see a way to get a real IMidiAccessManager on UWP

### ISSUE THREAD

**Issue by voxoid0** [atsushieno/managed-midi#37]
Hi. In my UWP (Xamarin.Forms) app, MidiAccessManager.Default returns an instance of EmptyMidiAccess . How can I get an instance of the UwpAccessManager? Presumably that is what I want, and I don't know of a way to directly instantiate it by depending on the nuget package.

**Comment by atsushieno** [comment]
Hi. Maybe you are referencing managed-midi from a netstandard package? managed-midi needs to be directly referenced from the Uwp project so that the Uwp version of the assembly is resolved. The netstandard is a "bait" part of it which contains only Empty MidiAccess.

**Comment by voxoid0** [comment]
Hmm, I'm referencing it from the UWP app, and from a class within that project I cannot access UwpAccessManager nor its namespace `Commons.Music.Midi.UwpWithStub.Commons.Music.Midi.UwpMidi`

**Comment by atsushieno** [comment]
Okay, I think I found out why. Let me push possible fix and update package.

**Comment by atsushieno** [comment]
1.9.2 will (1) contain `Commons.Music.Midi.UwpMidi.UwpMidiAccess` (as well as the old one in the bogus namespace) and (2) it will be set as MidiAccessManager.Default. Thanks for the report!

**Comment by voxoid0** [comment]
Nice, thanks for your fast help!
