### ISSUE TITLE
Hard to avoid deadlock when using IMidiAccess.Inputs and .Outputs 

### ISSUE THREAD

**Issue by voxoid0** [atsushieno/managed-midi#39]
At least with the UWP impl, I was getting deadlock because of that GetResults() call on the UWP API call. I later found GetInputs() and GetOutputs() async methods, which solves my problem, but just wanted to make a note that in the next major version (or first major version 1.x?) these should probably be removed, so that the API isn't easy to misuse like I did.

(...FYI I'm not planning to start submitting 3 issues every day; it's just that I'm sprinting towards a deadline, and just now plugging this lib into the app's live functionality).

**Comment by atsushieno** [comment]
Thanks for the info. I have to say, I very rarely took care of UWP parts (I very rarely use Windows and development on Win10 Home is annoying) and those stupid code could have slipped in whenever I made some common API changes. I'll take a look later.

**Comment by atsushieno** [comment]
Could you describe why / how it was blocking at your code? Is there anything that a thread that executes those methods synchronously require thread context switching (like, UWP framework itself tries to show some UI in the middle of these method calls) ?

The managed-midi common interface basically follows what Web MIDI API does, and Web MIDI API [MidiAccess interface](https://webaudio.github.io/web-midi-api/#midiaccess-interface) simply returns those device maps synchronously. The API is based on the assumption that device listing, unlike opening device, won't block.

If device listing takes rationally long time, maybe we should start considering async-ification. So far, it would be annoying for IMidiAccess implementors to implement both async and sync versions of the methods.

Another idea is to implement it like a sync method, but returns a lazy collection that will fix items only at IEnumerator instantiation time.

In either way it is an API-breaking change that I would basically avoid. If it is only problems in UWP app model, I would rather keep current API while keeping UwpMidiAccess public (which is not always the case; AlsaMidiAccess is going non-public) and make those async methods accessible to users. RFC.

**Comment by atsushieno** [comment]
Apart from Inputs and Outputs, `Results` are eliminated from GetInputsAsync() and GetOutputsAsync() at 687fe5d. I'm closing this issue, assuming that the issue was actually about those methods. If there are still issues please feel free to reopen. Thanks.

**Comment by usagi64** [comment]
Testing UWP I found the same problem in the methods **OpenInputAsync** and **OpenOutputAsync** causing deadlock and/or System.InvalidOperationException: A method was called at an unexpected time.

Changing the following lines in Commons.Music.Midi.UwpShared/UwpMidiAccess.cs removing IAsyncOperation<TResult>.GetResults fixed these errors.

`- var input = MidiInPort.FromIdAsync (portId).GetResults ();`
`+ var input = await MidiInPort.FromIdAsync (portId);`
and
`- var output = MidiOutPort.FromIdAsync (portId).GetResults ();`
`+ var output = await MidiOutPort.FromIdAsync (portId);`
May be commit 687fe5d was only half the way.
