### ISSUE TITLE
System exculsive bug

### ISSUE THREAD

**Issue by erano067** [atsushieno/managed-midi#43]
When sending some SysExc bytes it send it wrongly.

The command:
device.Send(new byte[] { 0xF0, 0x7F, 0x7F, 0x00, 0x00, 0x08, 0xF7 }, 0, 7, 0);

End-device got message:
[0x00, 0x7F, 0x00, 0x00, 0x00, 0x08, 0x00, 0x00] - 8 bytes long instead of 7 and missing data..

**Comment by atsushieno** [comment]
I assume it is related to UWP - I have no Windows environment to verify now so I only made a quick fix for suspicious bits of code. Please reopen it if it didn't fix the issue. Thanks.
