### ISSUE TITLE
Suggestion: Add a getting started guide

### ISSUE THREAD

**Issue by sbrl** [atsushieno/managed-midi#5]
For new users, digging through the code to figure out it works can be a daunting and confusing. Having a link in the README to a quick getting started tutorial (and, optionally, an API reference) can aid users in learning how the library works.

**Comment by atsushieno** [comment]
That's a good call, I wanted to do that after I sorted out everything on all platforms, but for quickstart guide why not :-)

**Comment by atsushieno** [comment]
I have added introductory section on README at 87b2c7d. If you need more hints on anything further, please reopen it with comments. Thanks.
