### ISSUE TITLE
ReadProc delegate is GC'd on macOS

### ISSUE THREAD

**Issue by smoogipoo** [atsushieno/managed-midi#50]
The MidReadProc delegate is GC'd on macOS, leading to the following assertion:

`A callback was made on a garbage collected delegate of type 'Commons.Music.Midi!CoreMidi.CoreMidiInterop+MIDIReadProc::Invoke'.`

This is probably caused by https://github.com/atsushieno/managed-midi/blob/1d4adb2d1ebfe8ff9cb5878850c04f7d49f60df7/Commons.Music.Midi.DesktopShared/coremidi/CoreMidiInterop.cs#L323, which is not stored globally.

**Comment by atsushieno** [comment]
Thanks for the report! I think I'll just keep the ReadDispatch in the MidiInput instance. Will fix it later when I'm with Mac.

**Comment by atsushieno** [comment]
Should be fixed at d11d4e2.
