### ISSUE TITLE
Description properties via USB-Midi

### ISSUE THREAD

**Issue by Stan19** [atsushieno/managed-midi#55]
Hi, Atsushieno,

May be i'm doing somewthing wrong, but...
I  tried to connect  my small test app (xamarin.forms, andriod project) to two hardware synthesizers via USB. Connection works fine in both cases. I was able to send NoteOn and NoteOff messages,
But I met an issue that the description properties of the opened Output were not enough to identify type of connected synthesizer for further processing. Here is one example:

When connecting to Roland FA-06 the description properties were:
ID: = device2_port0 
Name: = 
Manufacturer: = Roland
Version: = 1.16
 
When connecting via app MidiScope, which demonstrates Andriod 6 midi features directly, I can see much more usefull info:
Product: = FA-06 08
Manufacturer: = Roland
and, in addition, inside USB-device structure there are two more important properties:
mVendorID=1410
mProductID=373

Could you please fix existing property "Name" and add two more properties "mVendorID" and "mProductID" to Output object?
Many thanks in advance!

**Comment by atsushieno** [comment]
Hi, thanks for the report!

### Name

Looks like your Roland device does not provide any information on `android.media.midi.MidiDeviceInfo.PortInfo`. It is probably how Android MIDI API retrieves information.

In the meantime I made a fix on MidiPortDetails.Name (in Android) to also provide device name too.

### other properties and overall MidiPortDetails properties in general

Unlike platform-specific API, managed-midi is to provide the most common subset of the MIDI API features, and the API is mostly based on how [Web MIDI API](https://webaudio.github.io/web-midi-api/) is designed. In Web MIDI API, there is no information about "device" and therefore device information is exposed only through `MidiPort` (in their API). There won't be additional (and distinct) device name property apart from port name in managed-midi.

If you need such platform-specific information, then you should write code per platform. Especially if you are only targeting Android, you should use Android.Media.Midi namespace in Xamarin.Android.

"Vendor ID" and "Product ID" are not going to be supported for the same reason. Those IDs are part of USB specification and it's too protocol specific to offer any feature in managed-midi.

**Comment by Stan19** [comment]
Hi, Atsushieno,
Just want to say Many Thanks for your Efforts! Great Job !
