### ISSUE TITLE
Parsing MIDI messages

### ISSUE THREAD

**Issue by JuanuMusic** [atsushieno/managed-midi#56]
Is there a class or extension to parse the Midi Bytes?
If not, do you have any leading points on how to implement reading midi messages?

**Comment by JuanuMusic** [comment]
Found something that might be useful for people that's just starting with MIDI messages (like me):
https://users.cs.cf.ac.uk/Dave.Marshall/Multimedia/node158.html

**Comment by atsushieno** [comment]
Maybe this is what you want: `MidiEvent.Convert(byte[], int, int)`

https://github.com/atsushieno/managed-midi/blob/92674dd/Commons.Music.Midi.Shared/SMF.cs#L312

**Comment by JuanuMusic** [comment]
Thanks!!
