### ISSUE TITLE
Abstraction to sending raw bytes?

### ISSUE THREAD

**Issue by sbrl** [atsushieno/managed-midi#9]
Hello again,

I'm having difficulty understanding how to send a MIDI note to a device, as there doesn't seem to be anything anywhere on what format the `byte[]` array should contain. To this end, could you point me in the direction of the classes / files I should analyse the source code for to get a better idea on how this works?

For example, I found [this in one of your child projects](https://github.com/atsushieno/xmmk/blob/b25dab7648737684a8ff2197d98567bf47564575/Xmmk/MainWindow.cs#L431), but I don't really understand what's going on there.

**Comment by atsushieno** [comment]
From README.md:

    there are MidiCC, MidiRpnType, MidiMetaType and MidiEvent fields (of type System.Byte) so that you don't have to remember the actual numbers.

That should be already helpful enough. I'm not going to add "abstractions" to messages because they can be quite too arbitrary and the meanings can vary if they are meant to be useful.

**Comment by sbrl** [comment]
Ah, I must have missed that. I'll take a look at those classes now, thanks!

**Comment by sbrl** [comment]
Thanks for the pointer! I've done some additional reading, and I think I understand how it works now - MIDI messages aren't as difficult to figure out as I thought they would be :P

I've found the [`MidiMessage`](https://github.com/atsushieno/managed-midi/blob/master/lib/base/SMF.cs#L91) class though - what's it for? It doesn't seem to be commented.

**Comment by atsushieno** [comment]
MidiMessage, or particularly its DeltaTime, can be used to calculate "appropriate timing to send the event" to the output, so that player can deal with latency that could happen by any chance.
